apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: marathon

resources:
  - namespace.yaml
  - secrets.yaml
  - postgres.yaml
  - redis.yaml
  - ted2srt.yaml
  - marathon-api.yaml
  - marathon-worker.yaml
  - marathon-monitor.yaml
  - marathon-bot.yaml
  - hpa.yaml
  - ingress.yaml
